language: python
before_install:
  - sudo apt-get update -q
  - sudo apt-get install pypy -y
install:
  - python setup.py develop
  - pip install tox
script: tox -e $TOXENV
notifications:
  email: false
env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=nightly
  - TOXENV=pypy
